In [1]:
import pandas as pd
import numpy as np

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\aleac\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\aleac\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\aleac\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\Users\aleac\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\Users\aleac\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "c:\Users\aleac\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\aleac\AppData\Local\Temp\ipykernel_15844\2162656668.py", line 1, in <module>
    import pandas as pd
  File "c:\Users\aleac\anaconda3\Lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas.compat import (
  File "c:\Users\aleac\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "c:\Users\aleac\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "c:\Users\aleac\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\aleac\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\aleac\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\aleac\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\Users\aleac\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\Users\aleac\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "c:\Users\aleac\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\Users\aleac\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\aleac\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\aleac\AppData\Local\Temp\ipykernel_15844\2162656668.py", line 1, in <module>
    import pandas as pd
  File "c:\Users\aleac\anaconda3\Lib\site-packages\pandas\__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "c:\Users\aleac\anaconda3\Lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "c:\Users\aleac\anaconda3\Lib\site-packages\pandas\_libs\__init__.py", line 17, in <module>
    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

ImportError: numpy.core.multiarray failed to import

In [2]:
data = pd.read_excel("../apac_aggregated.xlsx")
data.head()

,WEEK,REGION,COUNTRY,ADMIN1,EVENT_TYPE,SUB_EVENT_TYPE,EVENTS,FATALITIES,POPULATION_EXPOSURE,DISORDER_TYPE,ID,CENTROID_LATITUDE,CENTROID_LONGITUDE
0,2016-12-31,Caucasus and Central Asia,Afghanistan,Badakhshan,Battles,Armed clash,6,15,113469.0,Political violence,1,36.966,73.3417
1,2017-01-07,Caucasus and Central Asia,Afghanistan,Badakhshan,Battles,Armed clash,5,28,155849.0,Political violence,1,36.966,73.3417
2,2017-01-21,Caucasus and Central Asia,Afghanistan,Badakhshan,Battles,Armed clash,1,4,38453.0,Political violence,1,36.966,73.3417
3,2017-02-04,Caucasus and Central Asia,Afghanistan,Badakhshan,Battles,Armed clash,1,4,1308.0,Political violence,1,36.966,73.3417
4,2017-02-11,Caucasus and Central Asia,Afghanistan,Badakhshan,Battles,Armed clash,4,41,143199.0,Political violence,1,36.966,73.3417

In [3]:
my_data = data[data['COUNTRY'] == 'Myanmar']

my_data['YEAR'] = my_data['WEEK'].dt.year
my_data['MONTH'] = my_data['WEEK'].dt.month
my_data['DAY'] = my_data['WEEK'].dt.day

after_coup = my_data[(my_data['YEAR'] > 2021) | ((my_data['YEAR'] == 2021) & (my_data['MONTH'] >= 2))]
after_coup.head()

C:\Users\aleac\AppData\Local\Temp\ipykernel_15852\3449467705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_data['YEAR'] = my_data['WEEK'].dt.year
C:\Users\aleac\AppData\Local\Temp\ipykernel_15852\3449467705.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_data['MONTH'] = my_data['WEEK'].dt.month
C:\Users\aleac\AppData\Local\Temp\ipykernel_15852\3449467705.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_data['DAY'] = my_data['WEEK'].dt.day

,WEEK,REGION,COUNTRY,ADMIN1,EVENT_TYPE,SUB_EVENT_TYPE,EVENTS,FATALITIES,POPULATION_EXPOSURE,DISORDER_TYPE,ID,CENTROID_LATITUDE,CENTROID_LONGITUDE,YEAR,MONTH,DAY
113069,2021-05-15,Southeast Asia,Myanmar,Ayeyarwady,Battles,Armed clash,1,0,208498.0,Political violence,2043,17.1075,95.1442,2021,5,15
113070,2021-05-29,Southeast Asia,Myanmar,Ayeyarwady,Battles,Armed clash,1,1,208498.0,Political violence,2043,17.1075,95.1442,2021,5,29
113071,2021-06-05,Southeast Asia,Myanmar,Ayeyarwady,Battles,Armed clash,1,5,15032.0,Political violence,2043,17.1075,95.1442,2021,6,5
113072,2021-09-18,Southeast Asia,Myanmar,Ayeyarwady,Battles,Armed clash,1,0,16793.0,Political violence,2043,17.1075,95.1442,2021,9,18
113073,2021-10-02,Southeast Asia,Myanmar,Ayeyarwady,Battles,Armed clash,1,1,89249.0,Political violence,2043,17.1075,95.1442,2021,10,2

In [ ]:
political = after_coup[after_coup['DISORDER_TYPE'] == 'Political violence']

total_events = political.sum(numeric_only=True)['EVENTS']
deadly_events = political[political['FATALITIES'] > 0].sum(numeric_only=True)['EVENTS']

# exposure = political.sum(numeric_only=True)['POPULATION_EXPOSURE']
# total_deaths = political.sum(numeric_only=True)['FATALITIES']

print(total_events, deadly_events)

54937.0 42390.0
                   SUB_EVENT_TYPE  EVENTS  FATALITIES  POPULATION_EXPOSURE  \
0  Abduction/forced disappearance    2515           0           59085920.0
1                Air/drone strike    8533        7105          112311303.0
2                     Armed clash   20824       58021          352085970.0
3                          Attack    7543        8944          284582480.0
4                 Chemical weapon       2           0              30064.0

        ID  CENTROID_LATITUDE  CENTROID_LONGITUDE     YEAR  MONTH    DAY
0  2497913         24928.2623         117179.7134  2462678   8531  18708
1  3610026         35967.4580         169663.9597  3561903  11751  27618
2  6574242         64308.0242         309325.7518  6484178  21489  50009
3  5078336         49217.4032         238658.4164  5006588  16359  38305
4     4107            38.1756            195.3175     4046      7     11